services:
  db:
    build: .
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 30s
      retries: 3
  prest:
    image: prest/prest
    restart: on-failure
    links:
      - "db:db"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - PREST_PG_HOST=db
      - PREST_PG_USER=${POSTGRES_USER}
      - PREST_PG_PASS=${POSTGRES_PASSWORD}
      - PREST_PG_DATABASE=${POSTGRES_DB}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - PREST_DEBUG=true # remove comment to disable DEBUG mode
      - PREST_PG_CACHE=false
      - PREST_JWT_DEFAULT=false # toggle to use jwt
      - PREST_CACHE_ENABLED=false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
volumes:
  postgres_data: